version: "3.9"
services:
  temp-calc:
    build:
      dockerfile: app/Dockerfile
      context: .
    env_file:
      - app/.env.docker
    ports:
      - 8006:8080
    entrypoint: sh -c "npm --prefix /app run startPM"
    networks:
      - backend-network
    depends_on:
      postgres:
        condition: service_started

  postgres:
    build:
      dockerfile: postgres/Dockerfile
      context: .
    env_file:
      - app/.env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
    attachable: true
